from __future__ import annotations
from . import angle
__all__ = ['Scalar', 'angle']
class Scalar:
    value: float
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __float__(self) -> float:
        ...
    def __init__(self, value: float, quantity_name: str, unit_symbol: str) -> None:
        ...
    def __mul__(self, arg0: float) -> Scalar:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __truediv__(self, arg0: float) -> Scalar:
        ...
    @property
    def quantity_name(self) -> str:
        ...
    @property
    def unit_symbol(self) -> str:
        ...
